### ISSUE TITLE
RFC6555 support

### ISSUE THREAD

**Issue by biaxident** [TakahikoKawasaki/nv-websocket-client#112]
Hi! Thank you for the great library again!
We have major issue with nv-websocket-client that it has not correct ipv4 fallback when target host not reachable by ipv6. I'm talking about https://tools.ietf.org/html/rfc6555 and so called dual-stack hosts.
WebSocketFactory uses straightforward InetSocketAddress obtained by InetAddress.getByName() function instead of InetAddress.getAllByName() to handle all existing InetAdresses.
Is there are plans to add rfc6555 support to nv-websocket-client or is it possible to customize your library somehow to write it ourselves?
This issue is very critical for us, because we have a lot of complaints from our users about this.

**Comment by TakahikoKawasaki** [comment]
I read RFC 6555 and understood what the problem is.

If <code>java.net.Socket.[connect](http://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#connect-java.net.SocketAddress-int-)(SocketAddress endpoint, int timeout)</code> can be retried **even after it throws an exception without re-creation of the <code>Socket</code> instance**, it may be relatively easy to implement the code which tries all the addresses returned by <code>getAllByName()</code>.

@biaxident Could you investigate whether <code>Socket.connect()</code> can be called twice or more on the same <code>Socket</code> instance until <code>connect()</code> succeeds?

**Comment by biaxident** [comment]
Thank you for fast reply.
I've checked the behavior of calling `Socket.connect()` on already exceptioned socket.
Unfortunately, in this case the second connect completes with exception `java.net.ConnectException: failed to connect to ...: connect failed: EBADF (Bad file descriptor)`.

@TakahikoKawasaki Is it possible to recreate socket after exception is thrown?

**Comment by TakahikoKawasaki** [comment]
@biaxident Thank you for the investigation. I'll try to devise a mechanism for the issue described in RFC 6555. How urgent is this issue for you?

**Comment by biaxident** [comment]
Is pretty urgent. I think we will fork the repo and do it as soon as possible.

**Comment by vazir** [comment]
@TakahikoKawasaki Hi. Issue is listed as open. Any plans to fix it?

**Comment by sjkummer** [comment]
Also ran into this. People happen to have IPv6 enabled in their routers without having "real" IPv6 WAN connectivity. We may experience this more often, since more users & companies are starting their IPv6 journey.

**Comment by dbrgn** [comment]
I'm also affected by this. If a domain has both A and AAAA records, and if a device has a local IPv6 address but no proper routes set up, then connecting fails.

@biaxident could you maybe create a pull request against this repo with your implementation, so that the change can get upstreamed?
