### ISSUE TITLE
Error 1002 

### ISSUE THREAD

**Issue by Jshell91** [TakahikoKawasaki/nv-websocket-client#14]
Hello
Im trying to get an open socket to receive information every X, but the conection is closed after a little time. This is the line I get at disconnect:

WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=84,CloseCode=1002,Reason="At least one of the reserved bits of a frame is set: RSV1=true,RSV2=true,RSV3=true")

Im already using setExtended(true) but it doesn't work.

**Comment by TakahikoKawasaki** [comment]
It seems strange. I'll check the source code later.

**Comment by Jshell91** [comment]
Haven't changed a thing, but now im getting this:
WebSocketFrame(FIN=1,RSV1=0,RSV2=0,RSV3=0,Opcode=CLOSE,Length=32,CloseCode=1002,Reason="A control frame is fragmented.")

**Comment by TakahikoKawasaki** [comment]
It seems that data coming from your WebSocket server are misaligned. What WebSocket server are you using?

**Comment by Jshell91** [comment]
The WebSocketServer im using is LibwebSockects for C
https://libwebsockets.org/libwebsockets-api-doc.html
Im coding just the Client for Android

**Comment by TakahikoKawasaki** [comment]
Considering (1) that the errors you reported are inconsistent and (2) that you (or your team members) are developing a WebSocket server by yourself (or yourselves) using the libwebsockets API (I guess so because you showed a link to the API doc instead of a working server executable), it is natural to think that the root cause is on the server side.
