### ISSUE TITLE
can't connect

### ISSUE THREAD

**Issue by five-lei** [TakahikoKawasaki/nv-websocket-client#166]
com.neovisionaries.ws.client.OpeningHandshakeException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 403 Forbidden

**Comment by mehran22k** [comment]
i meet this problem too
just adding:
**ws.addHeader("Origin","app:myapp");**
solde my problem

**Comment by TakahikoKawasaki** [comment]
@five-lei There are many possible reasons that can cause `403 Forbidden`. As @mehran22k showed an example, that kind of issues can be solved by adding some HTTP headers in most cases. Otherwise, the configuration of the server is wrong. If "101 Switching Protocols" is not returned, it means that the server does not accept a WebSocket connection for some reasons.
