### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by flavio99** [TakahikoKawasaki/nv-websocket-client#80]
Hello Takahiko

First of all thanks for this amazing lib. My problem is, that when i start my client i get an 403 Forbidden error. 
(com.neovisionaries.ws.cli_ent.OpeningHandshakeException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 403 Forbidden)

This is my code:

```
 public static void main(String[] args) {
        try {
            WebSocket ws = new WebSocketFactory()
                    .createSocket("ws://127.0.0.1:8080/echo");
            try {
                ws.addProtocol("Websocket");
                ws.connect();
            } catch (WebSocketException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
            ws.addListener(new WebSocketAdapter() {
                @Override
                public void onTextMessage(WebSocket websocket, String message)
                        throws Exception {
                    System.out.print(message);
                }
            });
            ws.sendText("0|" + "{}");
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
```
Can you help me?

**Comment by TakahikoKawasaki** [comment]
403 Forbidden indicates that you don't have a permission to access the endpoint (`ws://127.0.0.1:8080/echo`). A typical root cause is [Basic Authentication](https://tools.ietf.org/html/rfc2617#section-2). In any case, 403 Forbidden is not an error related to WebSocket. So, the first step you should take is to find the root cause of 403 Forbidden.

FYI: <code>WebSocket.[setUserInfo(String id, Stringpassword)](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#setUserInfo-java.lang.String-java.lang.String-)</code> method can be used to include `Authorization` header for Basic Authentication in the opening handshake request.

**Comment by flavio99** [comment]
Thanks for the tip. It worked :+1:
