### ISSUE TITLE
UnknownHostException in Java and Android client

### ISSUE THREAD

**Issue by Yahor10** [TakahikoKawasaki/nv-websocket-client#89]
In java and Android i catch those errors:

 W/System.err: Caused by: java.net.UnknownHostException: Host is unresolved:
 W/System.err:     at java.net.Socket.connect(Socket.java:865)
W/System.err:     at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:110)

But with browser my url works fine.

Where is the problem could be?

**Comment by TakahikoKawasaki** [comment]
If you are using a Samsung device, Issue #74 may be able to give you some hints. Otherwise, more info is needed to narrow down the scope of the problem.

**Comment by martinvano** [comment]
I get this error when the device is not connected to the network. Do you check if the network is available before the connect?

**Comment by TakahikoKawasaki** [comment]
@Yahor10 I have no idea about the difference of the behavior between your browser and your application code, sorry.

The implementation of nv-websocket-client does not check network availability. I know `ConnectivityManager` in Android, but this library does not use it so that this library can work in any environment where Android-dependent API is not available. Therefore, network availability has to be checked by programmers who use this library.

**Comment by TakahikoKawasaki** [comment]
Basically, `UnknownHostException` is not a WebSocket issue. I recommend that you post a question to [Stack Overflow](http://stackoverflow.com).
