### ISSUE TITLE
Problem with 101 Switching Protocols along with status code 200 ok

### ISSUE THREAD

**Issue by mnomansadiq** [TakahikoKawasaki/nv-websocket-client#98]
Hi, I am getting a problem  can you tell me why i am receiving both handshake problem and status code 200 OK. 

Here is what my client logged:
Failed to open websocket: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 200 OK

**Comment by avasenin** [comment]
It's part of WebSocket protocol. According to RFC 6455 server should response with 101 Switching protocol. Otherwise it's not a WebSocket handshake.
See for more details https://tools.ietf.org/html/rfc6455#section-1.2

**Comment by TakahikoKawasaki** [comment]
@mnomansadiq Make sure that the URL your application is trying to access is configured as a WebSocket endpoint. The error message says that the URL behaved as a normal HTTP endpoint. See "[1.2. Protocol Overview](https://tools.ietf.org/html/rfc6455#section-1.2)" and "[1.3. Opening Handshake](https://tools.ietf.org/html/rfc6455#section-1.3)" in [RFC 6455](https://tools.ietf.org/html/rfc6455) (The WebSocket Protocol) for details about '101 Switching Protocols'.

**Comment by mustahsanGranjur** [comment]
I am facing same issue with status code 403

The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 403 Forbidden

What could be the workaround? Thanks in advance.

**Comment by TakahikoKawasaki** [comment]
@mustahsanGranjur First, try to find the root cause of "403 Forbidden". A typical reason is that the WebSocket endpoint requires **Basic Authentication** but your client application does not set necessary credentials when it accesses the WebSocket endpoint. If this is the case, use <code>[setUserInfo(String id, String password)](http://takahikokawasaki.github.io/nv-websocket-client/com/neovisionaries/ws/client/WebSocket.html#setUserInfo-java.lang.String-java.lang.String-)</code> method of <code>WebSocket</code> to set the necessary credentials.

**Comment by amsibsam** [comment]
hi im facing the same issue with status code 302 found, what is that mean ?
thanks before

**Comment by TakahikoKawasaki** [comment]
"403 Forbidden" indicates that your access was rejected by the server. In most cases, the reason is that necessary HTTP headers are missing. This is an issue BEFORE the WebSocket protocol starts.

"302 Found" indicates a redirection. nv-websocket-client has no plan to support redirection.
